name: Docker Deploy
description: Docker build, tag and push

inputs:
  registry:
    required: true
    description: Url of the image registry

  repository:
    required: true
    description: Name of the repository

  tag:
    required: false
    default: dev
    description: Tag of the built image

  dockerfile:
    required: false
    default: Dockerfile
    description: Location of the dockerfile

  npm-read-packages-token:
    required: false
    default: ''
    description: Token for reading NPM packages from private repositories

runs:
  using: 'composite'
  steps:
    - name: Build, tag and push image
      shell: bash
      id: docker_setup
      env:
        IMAGE_TAG: ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.tag }}
        NPM_READ_PACKAGES_TOKEN: ${{ inputs.npm-read-packages-token }}
        DOCKER_BUILDKIT: '1'
      run: |
        docker build -f ${{ inputs.dockerfile }} -t $IMAGE_TAG --secret id=NPM_READ_PACKAGES_TOKEN,env=NPM_READ_PACKAGES_TOKEN .
        docker push $IMAGE_TAG
