compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: true

enableMessageNames: false

nodeLinker: node-modules

npmRegistries:
  //npm.pkg.github.com:
    npmAuthToken: '${NPM_READ_PACKAGES_TOKEN:-}'

npmScopes:
  ingeno:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.pkg.github.com'

yarnPath: .yarn/releases/yarn-4.0.1.cjs
