name: Node Setup
description: Read .nvmrc, nvm use, cache and install

inputs:
  working-directory:
    description: The current working directory to setup node into
    required: false
    default: '.'

runs:
  using: 'composite'

  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      working-directory: ${{ inputs.working-directory }}

    - name: Cache Root Dependencies
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      uses: actions/cache@v3
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('./yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install Dependencies
      shell: bash
      run: yarn install --immutable
      working-directory: ${{ inputs.working-directory }}
