name: 'Global - Lint PR title'
on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  global--lint-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: ingeno/foundation-github-actions/actions/node-setup@v5

      - name: Lint PR title
        uses: kevintyj/prlint@main

  global--can-pull-request-merge:
    name: Lint PR title check was successful
    runs-on: ubuntu-latest
    needs:
      - repo--lint-pr-title

    steps:
      - shell: bash
        run: |
          echo "Lint PR title check was successful"
