name: 'Pull Request Changes'

run-name: ‼️ Pull Request Changes

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: DEPRECATION WARNING
        shell: bash
        run: echo "DEPRECATED - use global--lint-pr-title"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: ingeno/foundation-github-actions/actions/node-setup@v3.2.6

      - name: Lint PR title
        uses: kevintyj/prlint@main

  can-pull-request-merge:
    name: Lint PR title check was successful
    runs-on: ubuntu-latest
    needs:
      - lint-pr-title

    steps:
      - shell: bash
        run: |
          echo "Lint PR title check was successful"
